#
# Copyright 2011 Fernando Ribeiro
#
# This file is part of Progress Sonic ESB Utils.
#
# Progress Sonic ESB Utils is free software: you can redistribute it and/or modify it under the terms of the GNU Lesser General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# Progress Sonic ESB Utils is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License along with Progress Sonic ESB Utils. If not, see <http://www.gnu.org/licenses/>.
#
type.name=DBServiceType
type.displayName=DB Service
type.shortDesc=DB Service
type.defaultInstance=dev.DB
type.initParamNames=driver, url, username, password
type.runtimeParamNames=keepOriginalPart, messagePart

initParam.driver.name=driver
initParam.driver.displayName=Driver
initParam.driver.type=string
initParam.driver.required=true

initParam.url.name=url
initParam.url.displayName=URL
initParam.url.type=string
initParam.url.required=true

initParam.username.name=username
initParam.username.displayName=Username
initParam.username.type=string

initParam.password.name=password
initParam.password.displayName=Password
initParam.password.type=password

runtimeParam.keepOriginalPart.name=keepOriginalPart
runtimeParam.keepOriginalPart.displayName=Keep Original Part
runtimeParam.keepOriginalPart.type=boolean
runtimeParam.keepOriginalPart.required=true
runtimeParam.keepOriginalPart.defaultValue=false

runtimeParam.messagePart.name=messagePart
runtimeParam.messagePart.displayName=Message Part
runtimeParam.messagePart.type=integer(-1, 2147483647)
runtimeParam.messagePart.required=true
runtimeParam.messagePart.defaultValue=0